import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import packageJson from '../package.json' with { type: 'json' };
import { baseToolingFiles } from './tooling.js';
const presetDir = dirname(fileURLToPath(import.meta.url));
const agentsPath = [
    resolve(presetDir, '../../../AGENTS.md'),
    resolve(presetDir, '../../../../AGENTS.md'),
].find(existsSync) ?? '';
const agentsContent = agentsPath ? readFileSync(agentsPath, 'utf8') : '';
export const mcp = ({ name, description }) => ({
    'package.json': JSON.stringify({
        name,
        version: '0.0.0',
        description,
        private: true,
        type: 'module',
        agents: './AGENTS.md',
        packageManager: packageJson.packageManager,
        engines: {
            node: packageJson.engines.node,
        },
        workspaces: [
            'workspaces/*',
        ],
        scripts: {
            storybook: 'cross-env STORYBOOK_DISABLE_TELEMETRY=1 storybook dev -p 6006 --disable-telemetry',
            check: 'run-s lint build test',
            fix: "run-s 'fix:*'",
            start: "run-p 'start:*'",
            lint: "run-s 'lint:*'",
            build: "run-s 'build:*'",
            test: "run-s 'test:*'",
            'fix:prettier': 'prettier . --write',
            'fix:eslint': 'eslint . --fix',
            'start:mcp': 'sh workspaces/mcp/bin/start.sh',
            'lint:ts': 'tsc',
            'lint:prettier': 'prettier . --check',
            'lint:eslint': 'eslint .',
            'build:mcp': 'sh workspaces/mcp/bin/build.sh',
            'build:storybook': 'cross-env STORYBOOK_DISABLE_TELEMETRY=1 storybook build --quiet --disable-telemetry',
            'test:jest': 'jest --coverage=false',
            prebuild: 'rimraf dist',
            postinstall: 'husky',
        },
        dependencies: {
            '@modelcontextprotocol/sdk': packageJson.peerDependencies['@modelcontextprotocol/sdk'],
            '@vyriy/typescript-config': `^${packageJson.version}`,
            typescript: packageJson.peerDependencies.typescript,
            '@vyriy/prettier-config': `^${packageJson.version}`,
            prettier: packageJson.peerDependencies.prettier,
            '@vyriy/eslint-config': `^${packageJson.version}`,
            eslint: packageJson.peerDependencies.eslint,
            '@vyriy/jest-config': `^${packageJson.version}`,
            jest: packageJson.peerDependencies.jest,
            '@vyriy/storybook-config': `^${packageJson.version}`,
            storybook: packageJson.peerDependencies.storybook,
            '@vyriy/path': `^${packageJson.version}`,
            husky: packageJson.peerDependencies.husky,
            'npm-run-all2': packageJson.peerDependencies['npm-run-all2'],
            'cross-env': packageJson.peerDependencies['cross-env'],
            rimraf: packageJson.peerDependencies.rimraf,
            '@vyriy/webpack-config': `^${packageJson.version}`,
            tsx: packageJson.peerDependencies.tsx,
            webpack: packageJson.peerDependencies.webpack,
            'webpack-cli': packageJson.peerDependencies['webpack-cli'],
            '@vyriy/handler': `^${packageJson.version}`,
            '@vyriy/router': `^${packageJson.version}`,
            '@vyriy/server': `^${packageJson.version}`,
            zod: packageJson.peerDependencies.zod,
        },
    }, null, 2) + '\n',
    'README.md': `# MCP

Minimal Streamable HTTP MCP server generated by the Vyriy MCP preset.

The project contains one runtime workspace:

- \`workspaces/mcp\` - MCP server exposed over \`/mcp\` with one \`hello_world\` tool.

## Requirements

- Node.js \`>=24.0.0\`
- Yarn \`4.17.0\`

## Install

\`\`\`bash
yarn install
\`\`\`

## Run

\`\`\`bash
yarn start:mcp
\`\`\`

The default MCP endpoint is:

\`\`\`txt
http://localhost:3000/mcp
\`\`\`

The healthcheck endpoint is:

\`\`\`txt
http://localhost:3000/healthcheck
\`\`\`

Override the bind address or port when needed:

\`\`\`bash
HOST=0.0.0.0 PORT=3003 yarn start:mcp
\`\`\`

## Call The Tool

\`\`\`bash
curl -s http://localhost:3000/mcp \\
  -H 'content-type: application/json' \\
  -H 'accept: application/json, text/event-stream' \\
  -d '{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"hello_world","arguments":{"name":"Vyriy"}}}'
\`\`\`

The tool returns a text response:

\`\`\`txt
Hello, Vyriy!
\`\`\`

## Build

\`\`\`bash
yarn build:mcp
\`\`\`

The build writes the production bundle and package metadata to \`dist\`.

## Validate

\`\`\`bash
yarn lint
yarn test
yarn build
\`\`\`
`,
    'doc.mdx': `import { Meta, Markdown } from '@storybook/addon-docs/blocks';
import ReadMe from './README.md?raw';

<Meta title="MCP" />

<Markdown>{ReadMe}</Markdown>
`,
    'AGENTS.md': agentsContent,
    '.editorconfig': `# https://editorconfig.org
root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

indent_style = space
indent_size = 2

max_line_length = 100

[*.md]
trim_trailing_whitespace = false
max_line_length = off

[*.{yml,yaml}]
indent_size = 2

[*.json]
indent_size = 2

[*.{ts,tsx,js,jsx}]
indent_size = 2

[*.sh]
indent_size = 2
`,
    '.gitignore': `.yarn/*
!.yarn/cache
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/sdks
!.yarn/versions

.DS_Store
.idea
node_modules
coverage
dist
storybook-static
*storybook.log
consumer

.claude
.codex
.agents

!/**/.gitkeep
`,
    '.npmrc': 'engine-strict=true\n',
    '.nvmrc': 'lts/krypton\n',
    '.yarnrc.yml': 'nodeLinker: node-modules\nnpmMinimalAgeGate: 0\n',
    '.husky/commit-msg': '#!/bin/sh\n',
    '.husky/post-checkout': '#!/bin/sh\n\nyarn\n',
    '.husky/post-merge': '#!/bin/sh\n\nyarn\n',
    '.husky/pre-commit': '#!/bin/sh\n\nyarn check\n',
    '.husky/pre-push': '#!/bin/sh\n\nyarn check\n',
    'yarn.lock': '',
    ...baseToolingFiles,
    '.prettierignore': 'node_modules\ndist\ncoverage\nstorybook-static\nconsumer\n',
    'workspaces/mcp/bin/build.sh': `#!/usr/bin/env sh

set -e

scriptdir="$PWD/workspaces/mcp"

NODE_ENV=production npx webpack --config "$scriptdir/webpack.config.ts"

cp "$scriptdir/package.json" dist/package.json
npm pkg delete "type" --prefix dist
npm pkg delete "private" --prefix dist
npm install --prefix dist
rm dist/package-lock.json
`,
    'workspaces/mcp/bin/start.sh': `#!/usr/bin/env sh

set -e

: "\${LOG_LEVEL:=info}"
: "\${HOST:=0.0.0.0}"
: "\${PORT:=3000}"

printf 'MCP endpoint: http://%s:%s/mcp\\n' "$HOST" "$PORT" >&2

exec env NODE_ENV=production LOG_LEVEL="$LOG_LEVEL" HOST="$HOST" PORT="$PORT" node --import tsx "$PWD/workspaces/mcp/index.ts"
`,
    'workspaces/mcp/doc.mdx': `import { Meta, Markdown } from '@storybook/addon-docs/blocks';
import ReadMe from './README.md?raw';

<Meta title="Workspaces/MCP" />

<Markdown>{ReadMe}</Markdown>
`,
    'workspaces/mcp/README.md': `# @w/mcp

Streamable HTTP MCP server workspace.

The workspace exposes one default tool:

- \`hello_world\` - returns a greeting for the provided \`name\`.

## Run

\`\`\`bash
yarn start:mcp
\`\`\`

## Build

\`\`\`bash
yarn build:mcp
\`\`\`

## Test

\`\`\`bash
yarn jest workspaces/mcp --runInBand --coverage=false
\`\`\`
`,
    'workspaces/mcp/webpack.config.ts': `import { path } from '@vyriy/path';
import { ssr, external } from '@vyriy/webpack-config';

export default ssr(
  '@w/mcp',
  {
    path: path('dist'),
    filename: 'index.js',
    library: { type: 'commonjs2' },
  },
  (config) => ({
    ...config,
    externals: [external({ allowlist: [/^@w/, /^@vyriy/] })],
  }),
);
`,
    'workspaces/mcp/package.json': JSON.stringify({
        name: '@w/mcp',
        version: '0.0.0',
        private: true,
        type: 'module',
        dependencies: {
            '@modelcontextprotocol/sdk': packageJson.peerDependencies['@modelcontextprotocol/sdk'],
            zod: packageJson.peerDependencies.zod,
        },
    }, null, 2) + '\n',
    'workspaces/mcp/types.ts': `import type { z } from 'zod';

export type ToolResult = {
  content: Array<{
    type: 'text';
    text: string;
  }>;
};

export type ToolDefinition<Input extends z.ZodRawShape> = {
  name: string;
  description: string;
  inputSchema: Input;
  handler: (input: z.infer<z.ZodObject<Input>>) => ToolResult | Promise<ToolResult>;
};
`,
    'workspaces/mcp/mcp.ts': `import type { z } from 'zod';
import type { ToolCallback } from '@modelcontextprotocol/sdk/server/mcp.js';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z as schema } from 'zod';

import type { ToolDefinition } from './types.js';

const helloWorldTool = {
  name: 'hello_world',
  description: 'Return a small hello-world greeting.',
  inputSchema: {
    name: schema.string().default('world').describe('Name to greet.'),
  },
  handler: ({ name }) => ({
    content: [
      {
        type: 'text',
        text: \`Hello, \${name}!\`,
      },
    ],
  }),
} satisfies ToolDefinition<{
  name: z.ZodDefault<z.ZodString>;
}>;

const registerTool = <Input extends z.ZodRawShape>(server: McpServer, tool: ToolDefinition<Input>) => {
  const callback = ((args: unknown) => tool.handler(args as z.infer<z.ZodObject<Input>>)) as ToolCallback<Input>;

  server.registerTool(
    tool.name,
    {
      description: tool.description,
      inputSchema: tool.inputSchema,
    },
    callback,
  );
};

export const createMcpServer = () => {
  const server = new McpServer({
    name: '@w/mcp',
    version: '0.0.0',
  });

  registerTool(server, helloWorldTool);

  return server;
};
`,
    'workspaces/mcp/server.ts': `import type { IncomingMessage, ServerResponse } from 'node:http';
import type { AddressInfo } from 'node:net';

import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import { create } from '@vyriy/handler';
import { createHttpRouter } from '@vyriy/router';
import { httpServer } from '@vyriy/server';
import { getBody } from '@vyriy/server/body';

import { createMcpServer } from './mcp.js';

const HTTP_HEADERS = {
  'access-control-allow-headers': 'content-type, mcp-protocol-version',
  'access-control-allow-methods': 'GET, POST, OPTIONS',
  'access-control-allow-origin': '*',
  'x-content-type-options': 'nosniff',
};

const json = (res: ServerResponse, statusCode: number, body: unknown) => {
  res.writeHead(statusCode, { 'content-type': 'application/json; charset=utf-8' });
  res.end(JSON.stringify(body));
};

const jsonRpcError = (res: ServerResponse, statusCode: number, code: number, message: string) =>
  json(res, statusCode, {
    jsonrpc: '2.0',
    error: { code, message },
    id: null,
  });

const readJsonBody = async (req: IncomingMessage) => {
  const body = (await getBody(req))?.trim();

  return body ? (JSON.parse(body) as unknown) : undefined;
};

const handleMcpRequest = async (req: IncomingMessage, res: ServerResponse) => {
  if ((req.method ?? 'GET') !== 'POST') {
    jsonRpcError(res, 405, -32000, 'Method not allowed.');
    return;
  }

  const server = createMcpServer();
  const transport = new StreamableHTTPServerTransport({
    sessionIdGenerator: undefined,
  });

  try {
    const body = await readJsonBody(req);

    await server.connect(transport);
    await transport.handleRequest(req, res, body);
  } catch (error) {
    console.error(error);

    if (!res.headersSent) {
      jsonRpcError(res, 500, -32603, 'Internal server error.');
    }
  } finally {
    await transport.close();
    await server.close();
  }
};

export const createHttpHandler = () => {
  const router = createHttpRouter();

  router.all('/mcp', handleMcpRequest);

  router.fallback((_req, res) => {
    json(res, 404, {
      message: 'Not found.',
    });
  });

  return create.httpApi({
    headers: HTTP_HEADERS,
    healthcheck: {
      body: {
        ok: true,
        name: '@w/mcp',
        transport: 'streamable-http',
      },
    },
  })(router.handle());
};

export const startHttpServer = async () => {
  const server = httpServer(createHttpHandler());

  await new Promise<void>((resolve, reject) => {
    if (server.listening) {
      resolve();
      return;
    }

    server.once('error', reject);
    server.once('listening', resolve);
  });

  const address = server.address() as AddressInfo;

  console.warn(\`MCP HTTP server listening on http://localhost:\${address.port}/mcp\`);

  return server;
};
`,
    'workspaces/mcp/index.ts': `import { startHttpServer } from './server.js';

void startHttpServer().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
`,
    'workspaces/mcp/mcp.test.ts': `import { describe, expect, it, jest } from '@jest/globals';

const registerToolMock = jest.fn();

jest.mock('@modelcontextprotocol/sdk/server/mcp.js', () => ({
  McpServer: jest.fn().mockImplementation((config) => ({
    config,
    registerTool: registerToolMock,
  })),
}));

describe('workspaces/mcp/mcp.ts', () => {
  it('creates an MCP server with the hello_world tool', async () => {
    const { createMcpServer } = await import('./mcp.js');

    const server = createMcpServer();

    expect(server).toHaveProperty('config', {
      name: '@w/mcp',
      version: '0.0.0',
    });
    expect(registerToolMock).toHaveBeenCalledWith(
      'hello_world',
      expect.objectContaining({
        description: 'Return a small hello-world greeting.',
      }),
      expect.any(Function),
    );
  });
});
`,
    'workspaces/mcp/index.test.ts': `import { describe, expect, it, jest } from '@jest/globals';

const startHttpServerMock = jest.fn(() => Promise.resolve());

jest.mock('./server.js', () => ({
  startHttpServer: startHttpServerMock,
}));

describe('workspaces/mcp/index.ts', () => {
  it('starts the MCP HTTP server', async () => {
    await import('./index.js');

    expect(startHttpServerMock).toHaveBeenCalledTimes(1);
  });
});
`,
});
