import { createRequire } from 'node:module';
const requireFromPackage = createRequire(import.meta.url);
const resolveDependency = (request) => requireFromPackage.resolve(request);
const transformEsmPackages = [
    '@vyriy',
    'bail',
    'ccount',
    'character-entities',
    'comma-separated-tokens',
    'decode-named-character-reference',
    'devlop',
    'escape-string-regexp',
    'estree-util-[^/]+',
    'hast-util-[^/]+',
    'html-url-attributes',
    'is-plain-obj',
    'lowlight',
    'longest-streak',
    'markdown-table',
    'mdast-util-[^/]+',
    'micromark',
    'micromark-[^/]+',
    'property-information',
    'react-markdown',
    'rehype-highlight',
    'remark-[^/]+',
    'remark-gfm',
    'space-separated-tokens',
    'trim-lines',
    'trough',
    'unified',
    'unist-util-[^/]+',
    'vfile',
    'vfile-[^/]+',
    'web-namespaces',
    'zwitch',
].join('|');
const config = {
    clearMocks: true,
    collectCoverage: true,
    collectCoverageFrom: [
        '<rootDir>/**/*.{ts,tsx,js,jsx,mjs,cjs}',
        '!<rootDir>/**/*.d.ts',
        '!<rootDir>/**/*.stories.{ts,tsx}',
        '!<rootDir>/**/*.types.ts',
        '!<rootDir>/**/types.ts',
        '!<rootDir>/*.config.{ts,mjs}',
        '!<rootDir>/**/*.config.{ts,mjs}',
        '!<rootDir>/consumer/**',
    ],
    coverageDirectory: 'coverage',
    coveragePathIgnorePatterns: [
        '/node_modules/',
        '<rootDir>/storybook-static/',
        '<rootDir>/dist/',
        '<rootDir>/build/',
        '<rootDir>/bin/',
        '<rootDir>/packages/.*/bin/',
        '<rootDir>/.bin/',
        '<rootDir>/.storybook/',
        '<rootDir>/coverage/',
        '<rootDir>/.yarn/',
        '<rootDir>/e2e/',
        '<rootDir>/consumer/',
    ],
    coverageProvider: 'v8',
    coverageReporters: [
        'json',
        'text',
        'text-summary',
        'lcov',
        'clover',
        'cobertura',
    ],
    coverageThreshold: {
        global: {
            branches: 100,
            functions: 100,
            lines: 100,
            statements: 100,
        },
    },
    moduleFileExtensions: [
        'js',
        'mjs',
        'cjs',
        'jsx',
        'ts',
        'mts',
        'cts',
        'tsx',
        'json',
        'node',
    ],
    moduleNameMapper: {
        '^(\\.{1,2}/.*)\\.js$': '$1',
        '\\.(css|less|scss|sass|svg)$': resolveDependency('identity-obj-proxy'),
    },
    modulePathIgnorePatterns: [
        '/node_modules/',
        '<rootDir>/coverage/',
        '<rootDir>/dist/',
        '<rootDir>/storybook-static/',
        '<rootDir>/consumer/',
    ],
    reporters: [
        'default',
        [
            resolveDependency('jest-junit'),
            {
                outputDirectory: 'coverage',
                outputName: 'junit.xml',
            },
        ],
    ],
    resetMocks: false,
    restoreMocks: true,
    testEnvironment: resolveDependency('jest-environment-jsdom'),
    testMatch: ['**/?(*.)+(spec|test).?([mc])[jt]s?(x)'],
    testPathIgnorePatterns: [
        '/node_modules/',
        '<rootDir>/coverage/',
        '<rootDir>/dist/',
        '<rootDir>/storybook-static/',
        '<rootDir>/consumer/',
    ],
    transform: {
        '^.+\\.[tj]sx?$': [
            resolveDependency('@swc/jest'),
            {
                jsc: {
                    transform: {
                        react: {
                            runtime: 'automatic',
                        },
                    },
                },
            },
        ],
    },
    transformIgnorePatterns: [
        `/node_modules/(?!(${transformEsmPackages})/)`,
    ],
};
export default config;
