import { getEnv } from './env.js';
import { Stage } from './types.js';
export const getStage = () => getEnv('STAGE', Stage.Local);
export const LOCAL = Stage.Local;
export const isLocal = () => getStage() === Stage.Local;
export const DEV = Stage.Dev;
export const isDev = () => getStage() === Stage.Dev;
export const DEVELOP = Stage.Develop;
export const isDevelop = () => getStage() === Stage.Develop;
export const TEST = Stage.Test;
export const isTest = () => getStage() === Stage.Test;
export const TESTING = Stage.Testing;
export const isTesting = () => getStage() === Stage.Testing;
export const QA = Stage.Qa;
export const isQa = () => getStage() === Stage.Qa;
export const UAT = Stage.Uat;
export const isUat = () => getStage() === Stage.Uat;
export const STAGING = Stage.Staging;
export const isStaging = () => getStage() === Stage.Staging;
export const PREPROD = Stage.PreProd;
export const isPreProd = () => getStage() === Stage.PreProd;
export const PREPRODUCTION = Stage.PreProduction;
export const isPreProduction = () => getStage() === Stage.PreProduction;
export const FEATURE = Stage.Feature;
export const isFeature = () => getStage() === Stage.Feature;
export const HOTFIX = Stage.Hotfix;
export const isHotfix = () => getStage() === Stage.Hotfix;
export const PRODUCTION = Stage.Production;
export const isProduction = () => getStage() === Stage.Production;
