import { GetEnvWithValue, Stage, IsStage } from './types.js';
export declare const getStage: GetEnvWithValue<Stage>;
export declare const LOCAL = Stage.Local;
export declare const isLocal: IsStage;
export declare const DEV = Stage.Dev;
export declare const isDev: IsStage;
export declare const DEVELOP = Stage.Develop;
export declare const isDevelop: IsStage;
export declare const TEST = Stage.Test;
export declare const isTest: IsStage;
export declare const TESTING = Stage.Testing;
export declare const isTesting: IsStage;
export declare const QA = Stage.Qa;
export declare const isQa: IsStage;
export declare const UAT = Stage.Uat;
export declare const isUat: IsStage;
export declare const STAGING = Stage.Staging;
export declare const isStaging: IsStage;
export declare const PREPROD = Stage.PreProd;
export declare const isPreProd: IsStage;
export declare const PREPRODUCTION = Stage.PreProduction;
export declare const isPreProduction: IsStage;
export declare const FEATURE = Stage.Feature;
export declare const isFeature: IsStage;
export declare const HOTFIX = Stage.Hotfix;
export declare const isHotfix: IsStage;
export declare const PRODUCTION = Stage.Production;
export declare const isProduction: IsStage;
