import type { GetStage, IsStage } from './types.js';
export declare const LOCAL = "local";
export declare const DEV = "dev";
export declare const DEVELOP = "develop";
export declare const TEST = "test";
export declare const TESTING = "testing";
export declare const QA = "qa";
export declare const UAT = "uat";
export declare const STAGING = "staging";
export declare const PREPROD = "preprod";
export declare const PREPRODUCTION = "pre-production";
export declare const FEATURE = "feature";
export declare const HOTFIX = "hotfix";
export declare const PRODUCTION = "production";
export declare const getStage: GetStage;
export declare const isLocal: IsStage;
export declare const isDev: IsStage;
export declare const isDevelop: IsStage;
export declare const isTest: IsStage;
export declare const isTesting: IsStage;
export declare const isQa: IsStage;
export declare const isUat: IsStage;
export declare const isStaging: IsStage;
export declare const isPreProd: IsStage;
export declare const isPreProduction: IsStage;
export declare const isFeature: IsStage;
export declare const isHotfix: IsStage;
export declare const isProduction: IsStage;
