import type { PlanResult } from '../plan/types.js';
import type { FileMap } from './types.js';
export declare const baseToolingDeps: () => {
    '@vyriy/typescript-config': string;
    typescript: string;
    '@vyriy/prettier-config': string;
    prettier: string;
    '@vyriy/eslint-config': string;
    eslint: string;
    '@vyriy/jest-config': string;
    jest: string;
    '@vyriy/storybook-config': string;
    storybook: string;
    '@vyriy/path': string;
    husky: string;
    'npm-run-all2': string;
    'cross-env': string;
};
export declare const webpackDeps: () => {
    rimraf: string;
    '@vyriy/webpack-config': string;
    tsx: string;
    'webpack-cli': string;
};
export declare const reactDeps: () => {
    react: string;
    'react-dom': string;
    '@types/react': string;
    '@types/react-dom': string;
};
export declare const stylelintDeps: () => {
    '@vyriy/stylelint-config': string;
    stylelint: string;
};
export declare const serverDeps: () => {
    '@vyriy/handler': string;
    '@vyriy/server': string;
};
export declare const buildPackageJson: (options: Pick<PlanResult, "name" | "description">, workspaces: string[], scripts: Record<string, string>, dependencies: Record<string, string>) => string;
export declare const reactWorkspaceBaseScripts: () => {
    storybook: string;
    check: string;
    fix: string;
    start: string;
    lint: string;
    build: string;
    test: string;
    'fix:prettier': string;
    'fix:eslint': string;
    'fix:stylelint': string;
    'lint:ts': string;
    'lint:prettier': string;
    'lint:eslint': string;
    'lint:stylelint': string;
    'build:storybook': string;
    'test:jest': string;
    postinstall: string;
};
export declare const workspaceBaseScripts: () => {
    storybook: string;
    check: string;
    fix: string;
    start: string;
    lint: string;
    build: string;
    test: string;
    'fix:prettier': string;
    'fix:eslint': string;
    'lint:ts': string;
    'lint:prettier': string;
    'lint:eslint': string;
    'build:storybook': string;
    'test:jest': string;
    postinstall: string;
};
export declare const reactWorkspaceScripts: (workspaceName: string) => {
    storybook: string;
    check: string;
    fix: string;
    start: string;
    lint: string;
    build: string;
    test: string;
    'fix:prettier': string;
    'fix:eslint': string;
    'fix:stylelint': string;
    'lint:ts': string;
    'lint:prettier': string;
    'lint:eslint': string;
    'lint:stylelint': string;
    'build:storybook': string;
    'test:jest': string;
    postinstall: string;
};
export declare const workspaceScripts: (workspaceName: string) => {
    storybook: string;
    check: string;
    fix: string;
    start: string;
    lint: string;
    build: string;
    test: string;
    'fix:prettier': string;
    'fix:eslint': string;
    'lint:ts': string;
    'lint:prettier': string;
    'lint:eslint': string;
    'build:storybook': string;
    'test:jest': string;
    postinstall: string;
};
export declare const stylelintConfigFile: () => FileMap;
export declare const assetsDeclarationFile: () => FileMap;
export declare const reactComponentFiles: () => FileMap;
export declare const reactServiceFiles: () => FileMap;
export declare const apiWorkspaceBaseFiles: (name: string, description: string) => FileMap;
