import type { CreateTableCommandInput } from '@aws-sdk/client-dynamodb';
import type { NativeAttributeValue } from '@aws-sdk/util-dynamodb';
import type { DeleteCommandInput, GetCommandInput, PutCommandInput, QueryCommandInput, ScanCommandInput, UpdateCommandInput } from '@aws-sdk/lib-dynamodb';
export type CreateTable = (params: CreateTableCommandInput) => Promise<void>;
export type Key = Record<string, NativeAttributeValue>;
export type Item = Record<string, unknown>;
export type CreateItem = (TableName: string, Item: Item, options?: Omit<PutCommandInput, 'TableName' | 'Item'>) => Promise<void>;
export type GetItem = (TableName: string, Key: Record<string, string | number>, options?: Omit<GetCommandInput, 'TableName' | 'Key'>) => Promise<Item | undefined>;
export type DeleteItem = (TableName: string, Key: Record<string, string | number>, options?: Omit<DeleteCommandInput, 'TableName' | 'Key'>) => Promise<void>;
export type UpdateItem = (TableName: string, Key: Record<string, string | number>, UpdateExpression: string, ExpressionAttributeValues?: Record<string, unknown>, options?: Omit<UpdateCommandInput, 'TableName' | 'Key' | 'UpdateExpression' | 'ExpressionAttributeValues'>) => Promise<void>;
export type GetItems = (TableName: string, keys: Record<string, unknown>, options?: Omit<QueryCommandInput, 'TableName'>) => Promise<unknown[]>;
export type GetAllItems = (TableName: string, options?: Omit<ScanCommandInput, 'TableName'>) => Promise<unknown[]>;
export type Handler = (items: unknown[]) => Promise<void>;
export type GetAllItemsWithHandler = (TableName: string, handler: Handler, options?: Omit<ScanCommandInput, 'TableName'>) => Promise<void>;
