import { getEnv } from './env.js';
export const LOCAL = 'local';
export const DEV = 'dev';
export const DEVELOP = 'develop';
export const TEST = 'test';
export const TESTING = 'testing';
export const QA = 'qa';
export const UAT = 'uat';
export const STAGING = 'staging';
export const PREPROD = 'preprod';
export const PREPRODUCTION = 'pre-production';
export const FEATURE = 'feature';
export const HOTFIX = 'hotfix';
export const PRODUCTION = 'production';
export const getStage = () => getEnv('STAGE', LOCAL);
export const isLocal = () => getStage() === LOCAL;
export const isDev = () => getStage() === DEV;
export const isDevelop = () => getStage() === DEVELOP;
export const isTest = () => getStage() === TEST;
export const isTesting = () => getStage() === TESTING;
export const isQa = () => getStage() === QA;
export const isUat = () => getStage() === UAT;
export const isStaging = () => getStage() === STAGING;
export const isPreProd = () => getStage() === PREPROD;
export const isPreProduction = () => getStage() === PREPRODUCTION;
export const isFeature = () => getStage() === FEATURE;
export const isHotfix = () => getStage() === HOTFIX;
export const isProduction = () => getStage() === PRODUCTION;
